/**
 * esbuild Configuration for CLI WebSocket Reconciler
 *
 * This bundles the server with import aliasing to redirect 'ink' imports
 * to our WebSocket-based shim, enabling the CLI's React components
 * to render over WebSocket instead of to a terminal.
 *
 * Strategy: Bundle only local code, keep all npm packages external.
 */

import * as esbuild from 'esbuild';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function build() {
  try {
    await esbuild.build({
      entryPoints: [path.join(__dirname, 'server/src/cli-reconciler-server.tsx')],
      bundle: true,
      platform: 'node',
      target: 'node20',
      outfile: path.join(__dirname, 'dist/cli-server.js'),
      format: 'esm',
      sourcemap: true,

      // CRITICAL: Redirect 'ink' imports to our shim
      alias: {
        'ink': path.join(__dirname, 'server/src/ink-shim/index.ts'),
      },

      // Keep all node_modules packages external - cleaner than listing each one
      packages: 'external',

      // TypeScript/JSX handling
      loader: {
        '.tsx': 'tsx',
        '.ts': 'ts',
        '.js': 'js',
        '.jsx': 'jsx',
      },

      // Handle .js extensions in imports
      resolveExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json'],

      logLevel: 'info',

      define: {
        'process.env.NODE_ENV': '"development"',
      },

      banner: {
        js: '// Generated by esbuild - CLI WebSocket Reconciler Server\n// ink module is aliased to our WebSocket shim',
      },
    });

    console.log('✅ Build complete: dist/cli-server.js');
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

build();
